### ISSUE TITLE
Sign up page issues

### ISSUE THREAD

**Issue by DaveSladeSewbrec** [NERC-CEH/lerc-wales-app#6]
Email input should use InputType=textEmailAddress 
Name inputs should use InputType=textCapSentences 
Also a checkbox to make the password visible, typing blind is silly if no one else is watching.
From Mike Evans via WWBIC

**Comment by ghost** [comment]
AKA EvansMike on GitHub who assumed it was a Java app not a JS one so my "InputType=" comments don't directly apply.
