### ISSUE TITLE
Welsh Species names

### ISSUE THREAD

**Issue by DaveSladeSewbrec** [NERC-CEH/lerc-wales-app#7]
Can we have a comment on the species name selection page that states that Welsh Species names are sadly not supported by the species dictionary?
Request via Cofnod
Dave

**Comment by kazlauskis** [comment]
Hi Dave, yes, I can add it in. What exactly would you like it to say?

**Comment by DaveSladeSewbrec** [comment]
Roy's suggestion is:

> The simplest way is to replace ‘Enw’, which is the place holder in the species name box with Enw (Gwyddonol neu Saesneg)
> 
> Which means ‘Name (scientific or English)’ . It’s an instruction and therefore doesn’t get embroiled in explaining or even apologising for the lack of Welsh dictionary.

**Comment by kazlauskis** [comment]
Yeah, I can add that or add a little explanation below if this is what you preferred.

**Comment by kazlauskis** [comment]
Just to double check, is this OK @DaveSladeSewbrec ? If yes, then I will push the app to app stores, thanks.

<img width="376" alt="screenshot 2018-10-21 at 22 20 54" src="https://user-images.githubusercontent.com/7383162/47272587-b93ac700-d57f-11e8-9e5c-4ab6196c03b0.png">
