### ISSUE TITLE
Email Invaild error

### ISSUE THREAD

**Issue by DaveSladeSewbrec** [NERC-CEH/lerc-wales-app#8]
Often when a user is trying to register a new account the phone gives an 'invalid email' error. In almost all of the examples I have encountered this is because the phone has 'helpfully' added a space character at the end of the email address having auto-filled the field on behalf of the user. 

Is is possible to get the app to look for and remove any space characters at the end of the email address on submission to allow the user to be unaware that their phone is messing with them and allow the registration to go through?
Dave

**Comment by kazlauskis** [comment]
Ah, that's interesting, thanks for reporting this. I will fix this.
